# Generated by Django 4.2.5 on 2023-09-26 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=64)),
                ('address', models.TextField(max_length=128)),
                ('birthday', models.TimeField()),
                ('bio', models.TextField(max_length=128)),
                ('education', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=64)),
                ('address', models.TextField(max_length=128)),
                ('numphone', models.CharField(max_length=15)),
            ],
        ),
    ]
