# Generated by Django 4.2.5 on 2023-09-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='address',
            field=models.TextField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='artist',
            name='birthday',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='education',
            field=models.TextField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(default='New artist', max_length=64),
        ),
    ]
