# Generated by Django 4.2.5 on 2023-09-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_artist_address_alter_artist_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='address',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='artist',
            name='birthday',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='artist',
            name='education',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
