# Generated by Django 4.2.5 on 2023-09-27 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_artist_address_alter_artist_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.owner')),
                ('name', models.CharField(max_length=128)),
                ('acreage', models.IntegerField()),
                ('address', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('execution', models.CharField(choices=[('paint', 'paint'), ('watercolor', 'watercolor'), ('sculpture', 'sculpture')])),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('volume', models.IntegerField(blank=True)),
            ],
        ),
    ]
