# Generated by Django 4.2.5 on 2023-09-27 11:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gallery_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.artist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
