# Generated by Django 4.2.5 on 2023-09-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_work_artist_alter_work_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
