# Generated by Django 4.2.5 on 2023-09-28 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_work_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_time', models.TextField(max_length=10)),
                ('end_time', models.TextField(max_length=10)),
                ('type', models.CharField(choices=[('paint', 'paint'), ('watercolor', 'watercolor'), ('sculpture', 'sculpture')])),
                ('num_of_tickets', models.IntegerField()),
                ('quantity_sold', models.IntegerField()),
                ('price', models.IntegerField()),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gallery')),
            ],
        ),
    ]
