# Generated by Django 4.2.5 on 2023-09-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_exhibit_quantity_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='img',
            field=models.ImageField(blank=True, default='default.png', upload_to='artists'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='img',
            field=models.ImageField(blank=True, upload_to='exhibits'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='img',
            field=models.ImageField(blank=True, upload_to='galleries'),
        ),
        migrations.AddField(
            model_name='owner',
            name='img',
            field=models.ImageField(blank=True, default='default.png', upload_to='owners'),
        ),
        migrations.AddField(
            model_name='work',
            name='img',
            field=models.ImageField(blank=True, upload_to='works'),
        ),
    ]
