# Generated by Django 4.2.5 on 2023-10-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_owner_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="img",
            field=models.ImageField(
                blank=True,
                default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzCb4DonWw5pT1-A3Su9HzG6TTN4nMOmj7tg&usqp=CAU",
                upload_to="artists",
            ),
        ),
    ]
