# Generated by Django 4.2.5 on 2023-10-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_artist_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="img",
            field=models.ImageField(
                blank=True, default="default/default.png", upload_to="artists"
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="img",
            field=models.ImageField(
                blank=True, default="default/default.png", upload_to="owners"
            ),
        ),
    ]
