# Generated by Django 4.2.5 on 2023-10-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_gallery_description_place_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
