# Generated by Django 4.2.5 on 2023-10-06 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_work_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exhibit')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.work')),
            ],
        ),
    ]
