# Generated by Django 4.2.5 on 2023-10-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_cart_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
